[workspace]
members = ["plonky2_recursion", "plonky2_sig_hash", "plonky2_ed25519", "plonky2_sha256", "plonky2_sha512"]
[workspace.package]
version = "0.1.0"
authors = ["Zpoken"]
description = "ZKP for NEAR"
edition = "2021"

[workspace.dependencies]
plonky2 = { git = "https://github.com/tikhono/plonky2", rev = "d1bc376b85abd2d9952da5b26ec1f45f3dc11985" }
plonky2_util = { git = "https://github.com/tikhono/plonky2", rev = "d1bc376b85abd2d9952da5b26ec1f45f3dc11985" }
plonky2_field = { git = "https://github.com/tikhono/plonky2", rev = "d1bc376b85abd2d9952da5b26ec1f45f3dc11985" }
plonky2_u32 = { git = "https://github.com/tikhono/plonky2", rev = "d1bc376b85abd2d9952da5b26ec1f45f3dc11985" }
plonky2_ecdsa  = { git = "https://github.com/tikhono/plonky2", rev = "d1bc376b85abd2d9952da5b26ec1f45f3dc11985" }
plonky2_sha256 = { path = "./plonky2_sha256" }
plonky2_sha512 = { path = "./plonky2_sha512" }
plonky2_ed25519 = { path = "./plonky2_ed25519" }

curve25519-dalek = { git = "https://github.com/tikhono/curve25519-dalek", rev = "c87a7edfbc5694a581ef30e39673622fabe0c7c5" }
anyhow = "1.0.40"
keccak-hash = "0.8.0"
itertools = "0.10.0"
log = "0.4.14"
sha2 = "0.10"
env_logger = "0.9.0"
rand = "0.8.4"
rand_chacha = "0.3.1"
rayon = "1.5.1"
serde = { version = "1.0", features = ["derive"] }
num = { version = "0.4", features = ["rand"] }
unroll = "0.1.5"
static_assertions = "1.1.0"
ed25519-compact = "2.0.4"

jemallocator = "0.5.0"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.test]
opt-level = 1